### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by ghost** [rschroll/efm#8]
Is there any way to change font size for ePub files using EFM with Monocle? I have tried to style the div containing book but it doesn't work.

**Comment by rschroll** [comment]
This is an issue with Monocle itself, not EFM.  I suspect what you want are these methods: https://github.com/joseph/Monocle/blob/62aacf7bed842d6aa57c2e9c4573fa8ff635cdc5/src/core/formatting.js#L49

**Comment by ghost** [comment]
Thank you for your help. I finally could find the solution adding font-size style to monocore.js.
